feat(events): add system events and event checks
ComposableFi/cosmwasm-vm-fork pull request #1
Opened 2022-08-04 21:58 UTC by aeryz

- Check and sanitize events and attributes.
- Add necessary system attributes and events.
- Refactor some namings.

Signed-off-by: aeryz <abdullaheryz@protonmail.com>

2022-08-05 08:12 UTC, dzmitry-lahoda commented on vm-wasmi/src/lib.rs
> +        // TODO(aeryz): we didn't want result but charge returns a result
i am ok with result:) or TODO: remove result from underlying API?

2022-08-05 08:17 UTC, dzmitry-lahoda commented on vm-wasmi/src/semantic.rs
> +                &BankAccount::try_from(self.env.contract.address.clone())
not sure, why we clone here? we call wasm or mulithreading on underlying API requries?

2022-08-05 08:22 UTC, dzmitry-lahoda commented on vm/src/vm.rs
> +    fn set_contract_meta(
not sure, may be name it `migrate`?  contracts address remains same after migration? just double check that Result<(), > is right

2022-08-05 08:30 UTC, dzmitry-lahoda reviewed
generally looks ok, like adding more metadata to to contract and that it?

2022-08-05 08:31 UTC, dzmitry-lahoda approved these changes

2022-08-05 14:55 UTC, KaiserKarel commented on vm-wasmi/src/lib.rs
> +        // TODO(aeryz): we didn't want result but charge returns a result
Is that a `todo` for removing later, or a general comment. Using `let _ = fallible()` is fine, and recommended to exlicitly show that we don't care about results. What does it imply if charge fails however?

2022-08-05 14:56 UTC, KaiserKarel commented on vm-wasmi/src/semantic.rs
> +                &BankAccount::try_from(self.env.contract.address.clone())
Everything inside a pallet is single-threaded anyway

2022-08-05 14:58 UTC, KaiserKarel commented on vm-wasmi/src/semantic.rs
> +                    .expect("contract address is set by vm, this should never happen"),
I would prefer if we could encode this in the type system to avoid the expect. We can have the VM store a BankAccount instead of address, or something fancier even, such as a struct wrapping the address with infallible conversion methods.

2022-08-05 14:58 UTC, KaiserKarel commented on vm-wasmi/src/semantic.rs
> +                    .expect("contract address is set by vm, this should never happen"),
expect/unwraps scare me

2022-08-05 15:04 UTC, KaiserKarel commented on vm/src/system.rs
> +}
Is there a reason for the associated const over a trait with an immutable receiver? This prevents implementations from having an HAS_CODE_ID based on fields, and thus is less flexible. Is that our intention?

2022-08-05 15:04 UTC, KaiserKarel commented on vm/src/system.rs
> +}
Same here, reason for assoicated const?

2022-08-05 15:05 UTC, KaiserKarel approved these changes

2022-08-06 12:29 UTC, hussein-aitlahcen commented on vm-wasmi/src/lib.rs
> +        // TODO(aeryz): we didn't want result but charge returns a result
This must be changed, charging the gas might fail, it must express it in the return type

2022-08-06 12:29 UTC, hussein-aitlahcen commented on vm-wasmi/src/semantic.rs
> +                    .expect("contract address is set by vm, this should never happen"),
Don't we have the `running_contract_meta` to avoid this???

2022-08-06 12:30 UTC, hussein-aitlahcen commented on vm/src/system.rs
> +}
Yeah this is system specific, I think we can make it public as we made  the underlying input public at the executor level. I doubt anyone will extend the even on this side but it's probably better   to keep it flexible

2022-08-06 12:31 UTC, hussein-aitlahcen commented on vm/src/system.rs
> +}
Btw the immutable receiver is fine, the const determine whether the type require the code id to be added to the event. This  is related to the type and not an instance of the type

2022-08-06 12:33 UTC, hussein-aitlahcen commented on vm/src/system.rs
> +}
This is value-per-type and not variable. We represent exports as types (see InstantiateInput, ExecuteInput etc.. in the executor). Hence, the implementation is generic over the function call, but there are small differences between then (i.e. the  event yield when the call is made, whether the code id of the contract must be added to the event etc...)

2022-08-06 12:33 UTC, hussein-aitlahcen commented on vm/src/system.rs
> +}
@aeryz lets make this public

2022-08-06 12:33 UTC, hussein-aitlahcen commented on vm/src/system.rs
> +}
@aeryz lets make this public

2022-08-06 12:34 UTC, hussein-aitlahcen commented on vm-wasmi/src/semantic.rs
> +                &BankAccount::try_from(self.env.contract.address.clone())
Clone doesn't mean it's multithreaded, you can't copy a Vec for instance. TryFrom consume the value, hence you need to clone.

2022-08-06 12:35 UTC, hussein-aitlahcen commented on vm-wasmi/src/lib.rs
> +        // TODO(aeryz): we didn't want result but charge returns a result
@aeryz you basically allow the user to do this call regardless of the gas counter, which must NEVER happen

2022-08-06 12:36 UTC, hussein-aitlahcen commented on vm/src/vm.rs
> +    fn set_contract_meta(
It's more low level than migrate, it's actually part of a migration

2022-08-06 12:37 UTC, hussein-aitlahcen requested changes
Overall good, but let's improve it a bit more :)

2022-08-06 12:50 UTC, aeryz commented on vm-wasmi/src/semantic.rs
> +                    .expect("contract address is set by vm, this should never happen"),
@hussein-aitlahcen this is the implementation of `running_contract_meta` 😄

2022-08-06 12:58 UTC, aeryz commented on vm-wasmi/src/semantic.rs
> +                    .expect("contract address is set by vm, this should never happen"),
@hussein-aitlahcen do we have scenario which we use some `Addr` type other than `BankAccount`? Because if the underlying string is not `u128`, `BankAccount::try_from` fails.

2022-08-09 14:06 UTC, merged